on: workflow_dispatch

name: checks

jobs:
  checks:
    runs-on: ubuntu-22.04
    env:
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.2.0'

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            rcmdcheck
            lintr

      - run: Rscript -e "errors <- lintr::lint_package(); print(errors); quit(save = 'no', status = length(errors))"
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"note"'
