on:
  workflow_dispatch:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            rcmdcheck
            devtools
            lintr
            rmarkdown
            knitr

      - run: Rscript -e "errors <- lintr::lint_package(); print(errors); quit(save = 'no', status = length(errors))"
      - run: Rscript -e "if (is.null(devtools::build_vignettes())) {message('ERROR. Devtools cannot find vignettes.'); quit(save = 'no', status = 1)}"
      - uses: r-lib/actions/check-r-package@v1
        with:
          error-on: '"note"'
